INSERT INTO ACCOUNT (NAME, PASSWORD) VALUES ('gesposito', '$2y$11$Bp4.XHl7OQEpdrF5cH9KGuSs1pZjyucpfoh7hjibPhoVErbzCKBWO');
INSERT INTO ACCOUNT (NAME, PASSWORD) VALUES ('jdoe', '$2y$11$m9fyuna0zyCK26k/jbEbrOU0nKblaueLSSoAdPt72R6mbhuXvq6T.');
INSERT INTO ACCOUNT (NAME, PASSWORD) VALUES ('pgomez', '$2y$11$HXKjVXJzDS6R97rhGpT//.2TAWmXHl2eNAH4.zvy3OZHsKF13ktL.');
INSERT INTO AUTH_ACCOUNT_GROUP (NAME, AUTH_GROUP) VALUES('gesposito', 'USER');
INSERT INTO AUTH_ACCOUNT_GROUP (NAME, AUTH_GROUP) VALUES('gesposito', 'ADMIN');
INSERT INTO AUTH_ACCOUNT_GROUP (NAME, AUTH_GROUP) VALUES('jdoe', 'USER');
INSERT INTO AUTH_ACCOUNT_GROUP (NAME, AUTH_GROUP) VALUES('pgomez', 'USER');